apiVersion: v1
kind: Service
metadata:
  name: cudgel-server
  namespace: cudgel-dev
spec:
  type: NodePort #  Expose on a port on each node.  Use LoadBalancer if you have a local LB.
  selector:
    app: cudgel-server
  ports:
    - port: 8080 #  The service port
      targetPort: 8080 #  The container port
      nodePort: 30001 #  The port on the node (choose an available one)
